<?php

namespace App\Plugins\Doctrine;

use Doctrine\DBAL\Platforms\AbstractPlatform;
use Doctrine\DBAL\Types\Type;

class DataTypes extends Type
{

    public function getSQLDeclaration(array $column, AbstractPlatform $platform)
    {
        // TODO: Implement getSQLDeclaration() method.
    }

    public function getName()
    {
        // TODO: Implement getName() method.
    }

    public function getMappedDatabaseTypes(AbstractPlatform $platform)
    {
        $types = parent::getMappedDatabaseTypes($platform);
        $types[] = "timestamp";
        return $types; // TODO: Change the autogenerated stub
    }
}
